library(TTR)
library(xlsx)
data1<-read.xlsx("StockData2.xlsx",2)
sapply(data1,class)
library(randomForest)
data1$Classification<-as.factor(data1$Classification)
frmla<- Classification ~ RSI+PERatio
model1<-randomForest(frmla,data1,na.action=na.exclude)
varImpPlot(model1)
Prediction <- predict(model1, data1)
submit <- data.frame(Date = data1$Date, Classification = Prediction)
cmat<-table(observed=data1$Classification,predicted=Prediction)
library(caret)
confusionMatrix(cmat)
write.csv(submit, file = "randomforest.csv", row.names = FALSE)
